language: ruby
rvm:
  - 2.1.0
addons:
  postgresql: "9.3"

before_script:
  - rm -rf config/database.yml
  - cp config/database.yml.travis config/database.yml
  - bin/rake db:create db:migrate
  - export CODECLIMATE_REPO_TOKEN=01deeac8bfb4f695eba38f08edb1fee2bf8ccd89556c0789cb915ad42f87ca82 
